### ISSUE TITLE
Issues after installing

### ISSUE THREAD

**Issue by Brin-o** [tiddly-gittly/slate-write#13]
Hello, i'm having an issue when clicking the edit button I only get this error. It's a single-file tiddlywiki.
![image](https://user-images.githubusercontent.com/49071768/192548224-7317817a-7a69-4127-978e-a0ee445c8609.jpeg)

**Comment by linonetwo** [comment]
install tw-react plugin, you can auto install dependdencies by using CPL https://github.com/tiddly-gittly/TiddlyWiki-CPL
