### ISSUE TITLE
控制按钮显示

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/slate-write#58]
比如在系统条目中，就不显示这个按钮。因为比如像控制台这种系统条目，一点击到这个按钮，就很有可能报错。

这个按钮应该只在非系统条目里展示。但现在我也想不到怎么解决。因为官方目前只有编辑栏的按钮可以控制范围，比如图片条目的按钮那几个就只有在编辑图片时才会显示出来。

类似的还有副标题，也不能做到控制显示。比如我做了一个副标题，但不需要在控制台这种系统条目里显示。

等会查查资料或者去论坛问问。

**Comment by linonetwo** [comment]
就是用 reveal 或者 list 微件来控制，然后控制好样式让它不显示的时候不挤占空白空间

**Comment by linonetwo** [comment]
可以参考 https://github.com/tiddly-gittly/zx-script/blob/master/src/zx-scripts/ViewToolbarButton.tid
