### ISSUE TITLE
条目里面包含内容的话，点击 所见所得 切换按钮就报错。

### ISSUE THREAD

**Issue by chxp2008** [tiddly-gittly/slate-write#7]
![image](https://user-images.githubusercontent.com/68766855/168013103-435d576c-e299-4cd9-a6af-7fc27973ef1f.png)
![image](https://user-images.githubusercontent.com/68766855/168013202-16483de5-b975-41f4-9356-a7a4a412a007.png)
怀疑和其他插件冲突

**Comment by linonetwo** [comment]
目前还只支持不含微件和宏的文本

**Comment by linonetwo** [comment]
v0.2.1 支持了
