### ISSUE TITLE
增加字段，用来排除筛选

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/slate-write#72]
![image](https://github.com/tiddly-gittly/slate-write/assets/109711900/5e349ba4-011b-4af2-9a2a-db3d55186a85)

我发现在这种组合形式的文本上，点击编辑按钮的话，会直接在页面上进行编辑。所以我想到应该加一个筛选字段，添加了这个字段和特定值，就不会出现这个编辑按钮。

我设置的是`no-slate-write`，值为`yes`的话，这个条目就不会出现这个按钮。

如果没啥问题的话，明天可以提pr。

![image](https://github.com/tiddly-gittly/slate-write/assets/109711900/ee775c49-328b-4251-838b-5f928c23df1c)

**Comment by linonetwo** [comment]
现在已经有筛选器，让他只在 tw5格式上才显示了，你可以再加一个  wysiwyg-disabled 字段

**Comment by dongrentianyu** [comment]
提交pr了。等合并了pr就可以关闭这个issue了。
